# coding: utf-8

"""
    nlpapiv2

    The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_nlp_api_client
from cloudmersive_nlp_api_client.api.analytics_api import AnalyticsApi  # noqa: E501
from cloudmersive_nlp_api_client.rest import ApiException


class TestAnalyticsApi(unittest.TestCase):
    """AnalyticsApi unit test stubs"""

    def setUp(self):
        self.api = cloudmersive_nlp_api_client.api.analytics_api.AnalyticsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_analytics_sentiment(self):
        """Test case for analytics_sentiment

        Perform Sentiment Analysis and Classification on Text  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
