# coding: utf-8

"""
    nlpapiv2

    The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_nlp_api_client
from cloudmersive_nlp_api_client.models.parse_request import ParseRequest  # noqa: E501
from cloudmersive_nlp_api_client.rest import ApiException


class TestParseRequest(unittest.TestCase):
    """ParseRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParseRequest(self):
        """Test ParseRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_nlp_api_client.models.parse_request.ParseRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
