# coding: utf-8

"""
    nlpapiv2

    The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_nlp_api_client
from cloudmersive_nlp_api_client.api.pos_tagger_api import PosTaggerApi  # noqa: E501
from cloudmersive_nlp_api_client.rest import ApiException


class TestPosTaggerApi(unittest.TestCase):
    """PosTaggerApi unit test stubs"""

    def setUp(self):
        self.api = cloudmersive_nlp_api_client.api.pos_tagger_api.PosTaggerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_pos_tagger_tag_adjectives(self):
        """Test case for pos_tagger_tag_adjectives

        Part-of-speech tag a string, filter to adjectives  # noqa: E501
        """
        pass

    def test_pos_tagger_tag_adverbs(self):
        """Test case for pos_tagger_tag_adverbs

        Part-of-speech tag a string, filter to adverbs  # noqa: E501
        """
        pass

    def test_pos_tagger_tag_nouns(self):
        """Test case for pos_tagger_tag_nouns

        Part-of-speech tag a string, filter to nouns  # noqa: E501
        """
        pass

    def test_pos_tagger_tag_pronouns(self):
        """Test case for pos_tagger_tag_pronouns

        Part-of-speech tag a string, filter to pronouns  # noqa: E501
        """
        pass

    def test_pos_tagger_tag_sentence(self):
        """Test case for pos_tagger_tag_sentence

        Part-of-speech tag a string  # noqa: E501
        """
        pass

    def test_pos_tagger_tag_verbs(self):
        """Test case for pos_tagger_tag_verbs

        Part-of-speech tag a string, filter to verbs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
