# coding: utf-8

"""
    nlpapi

    The powerful Natural Language Processing APIs let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_nlp_api_client
from cloudmersive_nlp_api_client.api.pos_tagger_json_api import PosTaggerJsonApi  # noqa: E501
from cloudmersive_nlp_api_client.rest import ApiException


class TestPosTaggerJsonApi(unittest.TestCase):
    """PosTaggerJsonApi unit test stubs"""

    def setUp(self):
        self.api = cloudmersive_nlp_api_client.api.pos_tagger_json_api.PosTaggerJsonApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_pos_tagger_json_post(self):
        """Test case for pos_tagger_json_post

        Part-of-speech tag a string  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
