# coding: utf-8

"""
    nlpapiv2

    The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_nlp_api_client
from cloudmersive_nlp_api_client.api.spellcheck_api import SpellcheckApi  # noqa: E501
from cloudmersive_nlp_api_client.rest import ApiException


class TestSpellcheckApi(unittest.TestCase):
    """SpellcheckApi unit test stubs"""

    def setUp(self):
        self.api = cloudmersive_nlp_api_client.api.spellcheck_api.SpellcheckApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_spellcheck_check_sentence(self):
        """Test case for spellcheck_check_sentence

        Check if sentence is spelled correctly  # noqa: E501
        """
        pass

    def test_spellcheck_correct_json(self):
        """Test case for spellcheck_correct_json

        Find spelling corrections  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
