# coding: utf-8

"""
    nlpapi

    The powerful Natural Language Processing APIs let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_nlp_api_client
from cloudmersive_nlp_api_client.api.words_api import WordsApi  # noqa: E501
from cloudmersive_nlp_api_client.rest import ApiException


class TestWordsApi(unittest.TestCase):
    """WordsApi unit test stubs"""

    def setUp(self):
        self.api = cloudmersive_nlp_api_client.api.words_api.WordsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_words_adjectives(self):
        """Test case for words_adjectives

        Get adjectives in string  # noqa: E501
        """
        pass

    def test_words_adverbs(self):
        """Test case for words_adverbs

        Get adverbs in input string  # noqa: E501
        """
        pass

    def test_words_get_words_json(self):
        """Test case for words_get_words_json

        Get words in input string (JSON)  # noqa: E501
        """
        pass

    def test_words_get_words_string(self):
        """Test case for words_get_words_string

        Get words from string  # noqa: E501
        """
        pass

    def test_words_nouns(self):
        """Test case for words_nouns

        Get nouns in string  # noqa: E501
        """
        pass

    def test_words_post(self):
        """Test case for words_post

        Get the verbs in a string  # noqa: E501
        """
        pass

    def test_words_pronouns(self):
        """Test case for words_pronouns

        Returns all pronounts in string  # noqa: E501
        """
        pass

    def test_words_proper_nouns(self):
        """Test case for words_proper_nouns

        Get proper nouns in a string  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
