# coding: utf-8

"""
    nlpapi

    The powerful Natural Language Processing APIs let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_nlp_api_client
from cloudmersive_nlp_api_client.models.check_json_response import CheckJsonResponse  # noqa: E501
from cloudmersive_nlp_api_client.rest import ApiException


class TestCheckJsonResponse(unittest.TestCase):
    """CheckJsonResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCheckJsonResponse(self):
        """Test CheckJsonResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_nlp_api_client.models.check_json_response.CheckJsonResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
