# coding: utf-8

"""
    nlpapiv2

    The powerful Natural Language Processing APIs (v2) let you perform part of speech tagging, entity identification, sentence parsing, and much more to help you understand the meaning of unstructured text.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_nlp_api_client
from cloudmersive_nlp_api_client.api.language_translation_api import LanguageTranslationApi  # noqa: E501
from cloudmersive_nlp_api_client.rest import ApiException


class TestLanguageTranslationApi(unittest.TestCase):
    """LanguageTranslationApi unit test stubs"""

    def setUp(self):
        self.api = cloudmersive_nlp_api_client.api.language_translation_api.LanguageTranslationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_language_translation_translate_deu_to_eng(self):
        """Test case for language_translation_translate_deu_to_eng

        Translate German to English text with Deep Learning AI  # noqa: E501
        """
        pass

    def test_language_translation_translate_eng_to_deu(self):
        """Test case for language_translation_translate_eng_to_deu

        Translate English to German text with Deep Learning AI  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
